-- ============================================================
-- BCC INTEGRATED DIGITAL PLAN REVIEW & APPROVAL SYSTEM
-- MySQL Database Schema
-- Generated: 2026-02-18
-- ============================================================
-- Create and select the database
CREATE DATABASE IF NOT EXISTS bcc_plans CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bcc_plans;
-- Disable FK checks during setup
SET FOREIGN_KEY_CHECKS = 0;
-- ============================================================
-- TABLE: plans_department
-- Must be created before plans_user (FK dependency)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_department (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT 1,
    display_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_department_name (name),
    KEY idx_department_order (display_order)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_user
-- Custom auth user — email-based login
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(254) NOT NULL,
    password VARCHAR(128) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    id_number VARCHAR(50) DEFAULT NULL,
    phone VARCHAR(20) NOT NULL DEFAULT '',
    role ENUM(
        'CLIENT',
        'RECEPTION',
        'STAFF',
        'EXECUTIVE',
        'ADMIN'
    ) NOT NULL DEFAULT 'CLIENT',
    department_id BIGINT DEFAULT NULL,
    is_active BOOLEAN NOT NULL DEFAULT 1,
    is_staff BOOLEAN NOT NULL DEFAULT 0,
    is_superuser BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    last_login DATETIME(6) DEFAULT NULL,
    -- Django auth fields
    last_login_django DATETIME(6) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_email (email),
    UNIQUE KEY uq_user_id_number (id_number),
    KEY idx_user_role (role),
    KEY idx_user_department (department_id),
    KEY idx_user_active (is_active),
    CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES plans_department (id) ON DELETE
    SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_architect
-- Registered architects (ZIBAC / ZIDA registry)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_architect (
    id BIGINT NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL,
    registration_no VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL DEFAULT '',
    phone VARCHAR(20) NOT NULL DEFAULT '',
    is_registered BOOLEAN NOT NULL DEFAULT 1,
    expiry_date DATE DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_architect_reg_no (registration_no),
    KEY idx_architect_registered (is_registered)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_standproperty
-- Stand / property registry (BCC jurisdiction)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_standproperty (
    id BIGINT NOT NULL AUTO_INCREMENT,
    stand_number VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    suburb VARCHAR(100) NOT NULL DEFAULT '',
    gps_lat DECIMAL(10, 7) DEFAULT NULL,
    gps_lng DECIMAL(10, 7) DEFAULT NULL,
    within_boundary BOOLEAN NOT NULL DEFAULT 1,
    rates_status ENUM(
        'CLEAR',
        'OUTSTANDING',
        'UNKNOWN'
    ) NOT NULL DEFAULT 'UNKNOWN',
    owner_name VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    UNIQUE KEY uq_stand_number (stand_number),
    KEY idx_stand_rates_status (rates_status),
    KEY idx_stand_within_boundary (within_boundary)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_plan
-- Core entity — one record per building plan application
-- plan_id format: BCC-YYYY-CAT-XXXX (generated by Django)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id VARCHAR(30) NOT NULL,
    client_id BIGINT NOT NULL,
    stand_id BIGINT NOT NULL,
    architect_id BIGINT DEFAULT NULL,
    category ENUM(
        'RESIDENTIAL',
        'COMMERCIAL',
        'INDUSTRIAL',
        'MIXED'
    ) NOT NULL,
    status ENUM(
        'DRAFT',
        'SUBMITTED',
        'PRE_SCREENING',
        'IN_REVIEW',
        'CORRECTIONS_REQUIRED',
        'REJECTED',
        'APPROVED'
    ) NOT NULL DEFAULT 'DRAFT',
    submitted_at DATETIME(6) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_plan_id (plan_id),
    KEY idx_plan_client (client_id),
    KEY idx_plan_stand (stand_id),
    KEY idx_plan_architect (architect_id),
    KEY idx_plan_status (status),
    KEY idx_plan_category (category),
    KEY idx_plan_created (created_at),
    CONSTRAINT fk_plan_client FOREIGN KEY (client_id) REFERENCES plans_user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_plan_stand FOREIGN KEY (stand_id) REFERENCES plans_standproperty (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_plan_architect FOREIGN KEY (architect_id) REFERENCES plans_architect (id) ON DELETE
    SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_planversion
-- Each file upload creates a new version (never overwritten)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_planversion (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    uploaded_by_id BIGINT NOT NULL,
    file VARCHAR(255) NOT NULL,
    file_type ENUM(
        'DWG',
        'PLN',
        'PDF',
        'OTHER'
    ) NOT NULL DEFAULT 'PDF',
    file_size_kb INT UNSIGNED NOT NULL DEFAULT 0,
    notes LONGTEXT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_planversion_plan_ver (plan_id, version_number),
    KEY idx_planversion_plan (plan_id),
    KEY idx_planversion_uploader (uploaded_by_id),
    CONSTRAINT fk_planversion_plan FOREIGN KEY (plan_id) REFERENCES plans_plan (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_planversion_uploader FOREIGN KEY (uploaded_by_id) REFERENCES plans_user (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_comment
-- Department review comments — one vote per department per version
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_comment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_version_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    text LONGTEXT NOT NULL,
    status_vote ENUM(
        'APPROVED',
        'CORRECTIONS_REQUIRED',
        'REJECTED'
    ) NOT NULL,
    is_internal BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_comment_planversion (plan_version_id),
    KEY idx_comment_department (department_id),
    KEY idx_comment_author (author_id),
    KEY idx_comment_vote (status_vote),
    KEY idx_comment_internal (is_internal),
    CONSTRAINT fk_comment_planversion FOREIGN KEY (plan_version_id) REFERENCES plans_planversion (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_comment_department FOREIGN KEY (department_id) REFERENCES plans_department (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES plans_user (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_flag
-- Pre-screening flags raised by reception
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_flag (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    plan_version_id BIGINT DEFAULT NULL,
    flag_type ENUM(
        'WARNING',
        'ERROR',
        'INFO'
    ) NOT NULL,
    category ENUM(
        'BOUNDARY',
        'RATES',
        'LEASE',
        'ARCHITECT',
        'AREA_MISMATCH',
        'DEPT_MISSING',
        'OTHER'
    ) NOT NULL,
    message LONGTEXT NOT NULL,
    is_resolved BOOLEAN NOT NULL DEFAULT 0,
    resolved_by_id BIGINT DEFAULT NULL,
    resolved_at DATETIME(6) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_flag_plan (plan_id),
    KEY idx_flag_planversion (plan_version_id),
    KEY idx_flag_type (flag_type),
    KEY idx_flag_resolved (is_resolved),
    CONSTRAINT fk_flag_plan FOREIGN KEY (plan_id) REFERENCES plans_plan (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_flag_planversion FOREIGN KEY (plan_version_id) REFERENCES plans_planversion (id) ON DELETE
    SET NULL ON UPDATE CASCADE,
        CONSTRAINT fk_flag_resolved_by FOREIGN KEY (resolved_by_id) REFERENCES plans_user (id) ON DELETE
    SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_receipt
-- Payment receipt — one per plan (OneToOne)
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_receipt (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    uploaded_by_id BIGINT NOT NULL,
    file VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    receipt_number VARCHAR(100) NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT 0,
    verified_by_id BIGINT DEFAULT NULL,
    verified_at DATETIME(6) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_receipt_plan (plan_id),
    KEY idx_receipt_verified (verified),
    KEY idx_receipt_uploader (uploaded_by_id),
    CONSTRAINT fk_receipt_plan FOREIGN KEY (plan_id) REFERENCES plans_plan (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_receipt_uploader FOREIGN KEY (uploaded_by_id) REFERENCES plans_user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_receipt_verified_by FOREIGN KEY (verified_by_id) REFERENCES plans_user (id) ON DELETE
    SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_approval
-- Final approval — irreversible, locked on creation
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_approval (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    approved_by_id BIGINT NOT NULL,
    signature_hash VARCHAR(512) NOT NULL,
    -- SHA-256 of plan+version+user+timestamp
    qr_code VARCHAR(255) DEFAULT NULL,
    timestamp DATETIME(6) NOT NULL,
    is_locked BOOLEAN NOT NULL DEFAULT 1,
    notes LONGTEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_approval_plan (plan_id),
    KEY idx_approval_approved_by (approved_by_id),
    KEY idx_approval_timestamp (timestamp),
    CONSTRAINT fk_approval_plan FOREIGN KEY (plan_id) REFERENCES plans_plan (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_approval_approved_by FOREIGN KEY (approved_by_id) REFERENCES plans_user (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- TABLE: plans_auditlog
-- Append-only audit trail — no UPDATEs or DELETEs ever
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_auditlog (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    target_model VARCHAR(100) NOT NULL,
    target_id INT UNSIGNED NOT NULL,
    old_value JSON DEFAULT NULL,
    new_value JSON DEFAULT NULL,
    ip_address VARCHAR(39) DEFAULT NULL,
    timestamp DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_auditlog_user (user_id),
    KEY idx_auditlog_action (action),
    KEY idx_auditlog_target_model (target_model),
    KEY idx_auditlog_target_id (target_id),
    KEY idx_auditlog_timestamp (timestamp),
    CONSTRAINT fk_auditlog_user FOREIGN KEY (user_id) REFERENCES plans_user (id) ON DELETE
    SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- Django auth support tables
-- (created by Django migrations — included here for reference)
-- ============================================================
CREATE TABLE IF NOT EXISTS django_migrations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    app VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    applied DATETIME(6) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS django_content_type (
    id INT NOT NULL AUTO_INCREMENT,
    app_label VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_content_type (app_label, model)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS auth_permission (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    content_type_id INT NOT NULL,
    codename VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_permission (content_type_id, codename),
    CONSTRAINT fk_permission_content_type FOREIGN KEY (content_type_id) REFERENCES django_content_type (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS plans_user_groups (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    group_id INT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_group (user_id, group_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS plans_user_user_permissions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    permission_id INT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_permission (user_id, permission_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
-- ============================================================
-- Re-enable FK checks
-- ============================================================
SET FOREIGN_KEY_CHECKS = 1;
-- ============================================================
-- SEED DATA: Departments
-- ============================================================
INSERT IGNORE INTO plans_department (name, is_required, display_order)
VALUES ('Town Planning', 1, 1),
    ('Building Inspections', 1, 2),
    ('Engineering', 1, 3),
    ('Environmental Health', 1, 4),
    ('Fire & Safety', 1, 5),
    ('Water & Sanitation', 0, 6),
    ('Electrical', 0, 7);
-- ============================================================
-- USEFUL VIEWS
-- ============================================================
-- Active plans with current status and version count
CREATE OR REPLACE VIEW v_plan_summary AS
SELECT p.id,
    p.plan_id,
    u.full_name AS client_name,
    u.email AS client_email,
    sp.stand_number,
    sp.address,
    a.full_name AS architect_name,
    p.category,
    p.status,
    p.submitted_at,
    p.created_at,
    COUNT(pv.id) AS version_count,
    SUM(
        CASE
            WHEN f.is_resolved = 0 THEN 1
            ELSE 0
        END
    ) AS open_flags
FROM plans_plan p
    JOIN plans_user u ON u.id = p.client_id
    JOIN plans_standproperty sp ON sp.id = p.stand_id
    LEFT JOIN plans_architect a ON a.id = p.architect_id
    LEFT JOIN plans_planversion pv ON pv.plan_id = p.id
    LEFT JOIN plans_flag f ON f.plan_id = p.id
GROUP BY p.id,
    p.plan_id,
    u.full_name,
    u.email,
    sp.stand_number,
    sp.address,
    a.full_name,
    p.category,
    p.status,
    p.submitted_at,
    p.created_at;
-- Department vote summary per plan version
CREATE OR REPLACE VIEW v_department_votes AS
SELECT pv.plan_id,
    p.plan_id AS plan_ref,
    pv.id AS version_id,
    pv.version_number,
    d.name AS department,
    d.is_required,
    c.status_vote,
    c.author_id,
    u.full_name AS reviewer,
    c.created_at AS voted_at
FROM plans_planversion pv
    JOIN plans_plan p ON p.id = pv.plan_id
    JOIN plans_comment c ON c.plan_version_id = pv.id
    JOIN plans_department d ON d.id = c.department_id
    JOIN plans_user u ON u.id = c.author_id;
-- Plans pending approval (all required depts approved, no approval record yet)
CREATE OR REPLACE VIEW v_ready_for_approval AS
SELECT p.id,
    p.plan_id,
    p.status,
    p.client_id,
    u.full_name AS client_name
FROM plans_plan p
    JOIN plans_user u ON u.id = p.client_id
WHERE p.status = 'IN_REVIEW'
    AND NOT EXISTS (
        SELECT 1
        FROM plans_approval ap
        WHERE ap.plan_id = p.id
    )
    AND NOT EXISTS (
        SELECT 1
        FROM plans_department d
        WHERE d.is_required = 1
            AND d.id NOT IN (
                SELECT c.department_id
                FROM plans_comment c
                    JOIN plans_planversion pv ON pv.id = c.plan_version_id
                WHERE pv.plan_id = p.id
                    AND c.status_vote = 'APPROVED'
                    AND pv.version_number = (
                        SELECT MAX(pv2.version_number)
                        FROM plans_planversion pv2
                        WHERE pv2.plan_id = p.id
                    )
            )
    );
-- ============================================================
-- END OF SCHEMA
-- ============================================================