import fitz
import io
import datetime
from django.core.files.base import ContentFile
from django.utils import timezone

class DocumentGenerator:
    @staticmethod
    def generate_intake_slip(plan):
        """Generates a PDF Intake Verification Slip."""
        doc = fitz.open()
        page = doc.new_page()
        
        # Header
        page.insert_text((50, 50), "CITY OF BULAWAYO", fontsize=20, fontname="helv-bold")
        page.insert_text((50, 75), "DEPARTMENT OF TOWN PLANNING", fontsize=14, fontname="helv-bold")
        page.insert_text((50, 100), "INTAKE VERIFICATION SLIP", fontsize=16, fontname="helv-bold", color=(0, 0, 0.8))
        
        # Details
        y = 150
        details = [
            ("Plan ID", plan.plan_id),
            ("Official Plan No", plan.plan_number or "PENDING"),
            ("Date Submitted", plan.submitted_at.strftime("%Y-%m-%d %H:%M") if plan.submitted_at else "N/A"),
            ("Client Name", plan.client.full_name),
            ("Stand Number", plan.stand.stand_number),
            ("Address", plan.stand.address),
            ("Category", plan.get_category_display()),
            ("Intake Status", "VERIFIED"),
        ]
        
        for label, value in details:
            page.insert_text((50, y), f"{label}:", fontsize=12, fontname="helv-bold")
            page.insert_text((200, y), str(value), fontsize=12, fontname="helv")
            y += 25
            
        # Footer
        page.insert_text((50, 750), f"Generated by Bulawayo PACS on {timezone.now().strftime('%Y-%m-%d %H:%M')}", fontsize=10, fontname="helv-italic")
        
        buffer = io.BytesIO()
        doc.save(buffer)
        doc.close()
        return buffer.getvalue()

    @staticmethod
    def generate_proforma_pdf(invoice):
        """Generates a PDF for a Proforma Invoice."""
        doc = fitz.open()
        page = doc.new_page()
        
        # Header
        page.insert_text((50, 50), "CITY OF BULAWAYO", fontsize=20, fontname="helv-bold")
        page.insert_text((50, 75), "PROFORMA INVOICE", fontsize=16, fontname="helv-bold", color=(0.8, 0, 0))
        page.insert_text((400, 50), f"Invoice #: {invoice.invoice_number}", fontsize=12, fontname="helv-bold")
        page.insert_text((400, 70), f"Date: {invoice.issued_at.strftime('%Y-%m-%d')}", fontsize=10)
        
        # Details
        page.insert_text((50, 120), f"Client: {invoice.plan.client.full_name}", fontsize=12)
        page.insert_text((50, 135), f"Plan ID: {invoice.plan.plan_id}", fontsize=12)
        page.insert_text((50, 150), f"Property: {invoice.plan.stand.address}", fontsize=12)
        
        # Table Header
        y = 200
        page.draw_line((50, y-5), (550, y-5))
        page.insert_text((50, y), "Description", fontsize=11, fontname="helv-bold")
        page.insert_text((300, y), "Vote No", fontsize=11, fontname="helv-bold")
        page.insert_text((400, y), "Amount (USD)", fontsize=11, fontname="helv-bold")
        page.insert_text((480, y), "Amount (ZWL)", fontsize=11, fontname="helv-bold")
        page.draw_line((50, y+15), (550, y+15))
        
        y += 35
        for item in invoice.line_items.all():
            page.insert_text((50, y), item.label[:40], fontsize=10)
            page.insert_text((300, y), item.vote_no, fontsize=10)
            page.insert_text((400, y), f"{item.amount_usd:,.2f}", fontsize=10)
            page.insert_text((480, y), f"{item.amount_zwl:,.2f}", fontsize=10)
            y += 20
            
        page.draw_line((50, y), (550, y))
        y += 20
        page.insert_text((300, y), "TOTAL DUE:", fontsize=12, fontname="helv-bold")
        page.insert_text((400, y), f"USD {invoice.total_usd:,.2f}", fontsize=12, fontname="helv-bold")
        page.insert_text((480, y), f"ZWL {invoice.total_zwl:,.2f}", fontsize=12, fontname="helv-bold")
        
        # Notes
        if invoice.notes:
            y += 50
            page.insert_text((50, y), "Notes:", fontsize=11, fontname="helv-bold")
            page.insert_textbox((50, y+5, 550, y+100), invoice.notes, fontsize=10)
            
        buffer = io.BytesIO()
        doc.save(buffer)
        doc.close()
        return buffer.getvalue()

    @staticmethod
    def generate_approval_certificate(plan, approval):
        """Generates a Final Approval Certificate."""
        doc = fitz.open()
        page = doc.new_page()
        
        # Border
        page.draw_rect((40, 40, 555, 782), color=(0, 0.4, 0), width=2)
        
        # Header
        page.insert_text((180, 80), "CITY OF BULAWAYO", fontsize=24, fontname="helv-bold", color=(0, 0.4, 0))
        page.insert_text((160, 110), "BUILDING APPROVAL CERTIFICATE", fontsize=18, fontname="helv-bold")
        
        # Plan Info
        y = 180
        page.insert_text((100, y), f"This is to certify that the plans for the proposed development at:", fontsize=12)
        y += 30
        page.insert_text((100, y), f"STAND NUMBER: {plan.stand.stand_number}", fontsize=13, fontname="helv-bold")
        y += 25
        page.insert_text((100, y), f"ADDRESS: {plan.stand.address}", fontsize=13, fontname="helv-bold")
        y += 40
        page.insert_text((100, y), f"SUBMITTED BY: {plan.client.full_name}", fontsize=12)
        y += 25
        page.insert_text((100, y), f"ARCHITECT: {plan.architect.full_name if plan.architect else 'N/A'}", fontsize=12)
        
        y += 50
        page.insert_text((100, y), f"Have been officially approved and assigned Plan Number:", fontsize=12)
        y += 35
        page.insert_text((100, y), plan.plan_number, fontsize=20, fontname="helv-bold", color=(0, 0.4, 0))
        
        y += 60
        page.insert_text((100, y), f"Approval Date: {approval.timestamp.strftime('%Y-%m-%d')}", fontsize=12)
        page.insert_text((100, y+20), f"Signature Hash: {approval.signature_hash[:32]}...", fontsize=8, color=(0.5, 0.5, 0.5))
        
        # QR Code
        if approval.qr_code:
            try:
                qr_img = io.BytesIO(approval.qr_code.read())
                page.insert_image((400, 550, 500, 650), stream=qr_img.getvalue())
            except:
                pass
        
        # Verification Link
        page.insert_text((100, 700), "This document is electronically generated and can be verified on the BCC PACS portal.", fontsize=10, fontname="helv-italic")
        
        buffer = io.BytesIO()
        doc.save(buffer)
        doc.close()
        return buffer.getvalue()
