# Generated by Django 5.2.11 on 2026-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pdf_pin_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='pdf_pin_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='calculated_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='declared_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PRE_SCREENING', 'Pre-Screening'), ('REVIEW_POOL', 'Review Pool'), ('IN_REVIEW', 'In Review'), ('CORRECTIONS_REQUIRED', 'Corrections Required'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('REJECTED_PRE_SCREEN', 'Rejected at Pre-Screening')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('RECEPTION', 'Reception'), ('DEPT_OFFICER', 'Department Officer'), ('DEPT_HEAD', 'Department Head'), ('FINAL_APPROVER', 'Final Approver'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
