# Generated by Django 5.2.11 on 2026-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_comment_pdf_pin_x_comment_pdf_pin_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signing_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
