# Generated by Django 5.2.11 on 2026-02-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_user_signing_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('MIXED', 'Mixed Use')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='plans.department')),
            ],
            options={
                'verbose_name': 'Workflow: Category to Department',
                'unique_together': {('category', 'department')},
            },
        ),
    ]
