# Generated by Django 5.2.11 on 2026-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_categorydepartmentmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='sealed_document',
            field=models.FileField(blank=True, null=True, upload_to='approved_plans/%Y/%m/'),
        ),
    ]
