# Generated by Django 5.2.11 on 2026-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_approval_sealed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='power_of_attorney',
            field=models.FileField(blank=True, null=True, upload_to='docs/auth/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='receipt_scan',
            field=models.FileField(blank=True, null=True, upload_to='docs/payments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='structural_cert',
            field=models.FileField(blank=True, null=True, upload_to='docs/technical/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='title_deed',
            field=models.FileField(blank=True, null=True, upload_to='docs/legal/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'Property Owner'), ('PROFESSIONAL', 'Registered Professional')], default='OWNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='declared_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('RECEPTION', 'Reception'), ('DEPT_OFFICER', 'Department Officer'), ('DEPT_HEAD', 'Department Head'), ('FINAL_APPROVER', 'Final Approver'), ('ADMIN', 'System Administrator')], default='CLIENT', max_length=20),
        ),
    ]
