# Generated by Django 5.2.11 on 2026-02-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_is_owner_plan_owner_name_plan_power_of_attorney_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='plans.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('OFFICER_APPROVED', 'Officer Approved'), ('OFFICER_CORRECTIONS', 'Officer Requested Corrections'), ('OFFICER_REJECTED', 'Officer Rejected'), ('HEAD_CONFIRMED', 'Head Confirmed'), ('HEAD_REJECTED', 'Head Rejected')], default='PENDING', max_length=30)),
                ('officer_comment', models.TextField(blank=True)),
                ('officer_acted_at', models.DateTimeField(blank=True, null=True)),
                ('head_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('OFFICER_APPROVED', 'Officer Approved'), ('OFFICER_CORRECTIONS', 'Officer Requested Corrections'), ('OFFICER_REJECTED', 'Officer Rejected'), ('HEAD_CONFIRMED', 'Head Confirmed'), ('HEAD_REJECTED', 'Head Rejected')], default='PENDING', max_length=30)),
                ('head_comment', models.TextField(blank=True)),
                ('head_acted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='plans.department')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_reviews', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_reviews', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reviews', to='plans.planversion')),
            ],
            options={
                'ordering': ['department__display_order'],
                'unique_together': {('plan_version', 'department')},
            },
        ),
    ]
