# Generated by Django 5.2.11 on 2026-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_workflowlog_departmentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('RECEPTION', 'Reception'), ('DEPT_OFFICER', 'Department Officer'), ('DEPT_HEAD', 'Department Head'), ('FINAL_APPROVER', 'Final Approver'), ('ADMIN', 'System Administrator')], default='CLIENT', max_length=50),
        ),
    ]
