# Generated by Django 5.2.11 on 2026-02-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stand_type',
            field=models.CharField(choices=[('RESIDENTIAL_HIGH_DENSITY', 'Residential High Density'), ('RESIDENTIAL_LOW_DENSITY', 'Residential Low Density'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('INSTITUTIONAL', 'Institutional')], default='RESIDENTIAL_HIGH_DENSITY', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='plan_documents/')),
                ('version_number', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='plans.plan')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
