# Generated by Django 5.2.11 on 2026-03-12 12:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_plan_stand_type_notification_plandocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], default='IN_APP', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default=datetime.datetime(2026, 3, 12, 12, 45, 47, 362518, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='is_representative',
            field=models.BooleanField(default=False, help_text='True if applicant is acting on behalf of the owner.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_number',
            field=models.CharField(blank=True, help_text='Official BUL/PACS/YYYY/XXXXXX number. Assigned only after payment & doc verification.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='represents_owner_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='represents_owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='submission_type',
            field=models.CharField(choices=[('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final')], default='PRELIMINARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRELIMINARY_SUBMITTED', 'Preliminary Submitted'), ('PROFORMA_ISSUED', 'Proforma Issued'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('DOCUMENTS_PENDING_VERIFICATION', 'Documents Pending Verification'), ('VERIFIED_BY_RECEPTION', 'Verified by Reception'), ('SUBMITTED', 'Submitted'), ('PRE_SCREENING', 'Pre-Screening'), ('FINAL_SUBMITTED', 'Final Submitted'), ('REVIEW_POOL', 'Review Pool'), ('IN_REVIEW', 'In Review'), ('CORRECTIONS_REQUIRED', 'Corrections Required'), ('AWAITING_FINAL_DECISION', 'Awaiting Final Decision'), ('REJECTED', 'Rejected'), ('REJECTED_PRE_SCREEN', 'Rejected at Pre-Screening'), ('APPROVED', 'Approved')], default='DRAFT', max_length=40),
        ),
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(help_text='Mandatory reason for the final decision.')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('final_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_decisions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_decision', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='payment_evidence/%Y/%m/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='plans.proformainvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('vote_no', models.CharField(blank=True, help_text='BCC vote number e.g. 0074/50363', max_length=50)),
                ('amount_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_rates_payment', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='plans.proformainvoice')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('is_rates_payment', models.BooleanField(default=False, help_text='When True, the receptionist can also add a rates payment amount to the proforma.')),
                ('is_optional', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='plans.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='submitted_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_documents', to='plans.plan')),
                ('required_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='plans.requireddocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
