# Generated by Django 5.2.11 on 2026-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_checklisttemplate_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='development_description',
            field=models.TextField(blank=True, help_text='e.g. church, factory, new residence, etc.', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='rates_comment',
            field=models.TextField(blank=True, help_text='Comment to clear rates balance.'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='reception_contacts',
            field=models.TextField(blank=True, help_text='Contacts for the client to follow up with.'),
        ),
    ]
