# Generated by Django 5.2.11 on 2026-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_plan_development_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentreview',
            options={'ordering': ['review_stage', 'department__display_order']},
        ),
        migrations.AlterUniqueTogether(
            name='departmentreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmentreview',
            name='amount_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='departmentreview',
            name='review_stage',
            field=models.CharField(choices=[('PRELIMINARY', 'Preliminary'), ('TECHNICAL', 'Technical')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='departmentreview',
            unique_together={('plan_version', 'department', 'review_stage')},
        ),
    ]
