# Generated by Django 5.2.11 on 2026-05-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_alter_departmentreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('RECTANGLE', 'Rectangle'), ('TRIANGLE', 'Triangle'), ('CIRCLE', 'Circle'), ('TRAPEZIUM', 'Trapezium'), ('L_SHAPE', 'L-Shaped Composite'), ('MANUAL', 'Manual Entry')], max_length=30)),
                ('dimensions', models.JSONField(default=dict)),
                ('declared_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('calculated_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tolerance_exceeded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('file_page_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometry_assessments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_assessments', to='plans.plan')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometry_assessments', to='plans.planversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeometryException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('GEOMETRY_UNAVAILABLE', 'Geometry unavailable'), ('INFORMATION_INCOMPLETE', 'Information incomplete'), ('DRAWING_UNCLEAR', 'Drawing unclear'), ('MANUAL_VERIFICATION_DONE', 'Manual verification done'), ('NOT_APPLICABLE', 'Not applicable'), ('OTHER', 'Other')], max_length=100)),
                ('justification', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('requires_follow_up', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometry_exceptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_exceptions', to='plans.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
