# Generated by Django 5.2.11 on 2026-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_geometryassessment_geometryexception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitteddocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='visibility_departments',
            field=models.CharField(blank=True, help_text='Comma-separated department codes.', max_length=255),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='plan_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('MIXED', 'Mixed Use')], max_length=50),
        ),
    ]
