# Generated by Django 5.2.11 on 2026-05-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_alter_submitteddocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_requirements', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='plans.checklisttemplate'),
        ),
    ]
